<?xml version="1.0"?>
<!DOCTYPE musées[
	<!ELEMENT musées (musée+, objet-art+)>
	<!ELEMENT musée (nom, ville, visites)>
	<!ATTLIST musée idmusée ID #REQUIRED>
	<!ELEMENT nom (#PCDATA)>
	<!ELEMENT ville (#PCDATA)>
	<!ELEMENT visites (visiteur+)>
	<!ELEMENT visiteur (#PCDATA)>
	<!ATTLIST visiteur date CDATA #REQUIRED
					   payé CDATA #REQUIRED>
	<!ELEMENT objet-art (intitulé, auteur?, description)>
	<!ATTLIST objet-art musée IDREF #REQUIRED
						type CDATA #REQUIRED>
	<!ELEMENT intitulé (#PCDATA)>
	<!ELEMENT auteur (#PCDATA)>
	<!ELEMENT description (#PCDATA|matériau)*>
	<!ELEMENT matériau (#PCDATA)*>
]>

<musées>
  <musée idmusée="lop">
    <nom>Louvre</nom><ville>Paris</ville>
    <visites>
      <visiteur date="2021-10-03" payé="8.50">Jean Dupont</visiteur>
      <visiteur date="2021-10-03" payé="5.00">Marie Dupont</visiteur>
    </visites>
  </musée>
  <musée idmusée="man">
    <nom>Matisse</nom><ville>Nice</ville>
    <visites>
      <visiteur date="2021-10-03" payé="8.00">Kévin Martin</visiteur>
      <visiteur date="2021-10-04" payé="10.00">Victor Martin</visiteur>
    </visites>
  </musée>
  <objet-art musée="lop" type= "peinture">
    <intitulé>La Joconde</intitulé>
    <auteur>Léonard de Vinci</auteur>
    <description>Peinture à l'<matériau>huile</matériau> sur <matériau>panneau de bois</matériau></description>
  </objet-art>
  <objet-art musée="lop" type="sculpture">
    <intitulé>Vénus de Milo</intitulé>
    <description>Statue grecque en <matériau>marbre</matériau></description>
  </objet-art>
</musées>
