=== Jiaqiii7/XML/src/fr/cergy/musee.xsd
<?xml version = "1.0"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:element name="musées" type="muséesType">
		<xsd:key name="muséeKey">
			<xsd:selector xpath="musée"/>
			<xsd:field xpath="@idmusée"/>
		</xsd:key>
		<xsd:keyref name="muséeRef" refer="muséeKey">
			<xsd:selector xpath="objet-art"/>
			<xsd:field xpath="@musée"/>
		</xsd:keyref>
	</xsd:element>

<xsd:complexType name="muséesType">
	<xsd:sequence>
		<xsd:element name="musée" type="muséeType" maxOccurs="unbounded"/>
		<xsd:element name="objet-art" type="objet-artType" maxOccurs="unbounded"/>
	</xsd:sequence>
</xsd:complexType>

<xsd:complexType name="muséeType">
	<xsd:sequence>
		<xsd:element name="nom" type="xsd:string"/>
		<xsd:element name="ville" type="xsd:string"/>
		<xsd:element name="visites" type="visitesType"/>
	</xsd:sequence>
	<xsd:attribute name="idmusée" type="xsd:string" use="required"/>
</xsd:complexType>

<xsd:complexType name="visitesType">
	<xsd:sequence>
		<xsd:element name="visiteur" type="visiteurType" maxOccurs="unbounded"/>
	</xsd:sequence>
</xsd:complexType>

<xsd:complexType name="visiteurType">
	<xsd:simpleContent>
		<xsd:extension base="xsd:string">
			<xsd:attribute name="date" type="xsd:date"/>
			<xsd:attribute name="payé" type="xsd:decimal"/>
		</xsd:extension>
	</xsd:simpleContent>
</xsd:complexType>

<xsd:complexType name="objet-artType">
	<xsd:sequence>
		<xsd:element name="intitulé" type="xsd:string"/>
		<xsd:element name="auteur" type="xsd:string" minOccurs="0"/>
		<xsd:element name="description" type="descriptionType"/>
	</xsd:sequence>
	<xsd:attribute name="musée" type="xsd:string" use="required"/>
	<xsd:attribute name="type" type="xsd:string" use="required"/>
</xsd:complexType>

<xsd:complexType name="descriptionType" mixed="true">
	<xsd:sequence>
		<xsd:element name="matériau" type="xsd:string" maxOccurs="unbounded"/>
	</xsd:sequence>
</xsd:complexType>

</xsd:schema>

=== Jiaqiii7/XML/src/fr/cergy/musee2.xml
<?xml version="1.0"?>

<musées xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
			  xsi:noNamespaceSchemaLocation="musee.xsd">
  <musée idmusée="lop">
    <nom>Louvre</nom><ville>Paris</ville>
    <visites>
      <visiteur date="2021-10-03" payé="8.50">Jean Dupont</visiteur>
      <visiteur date="2021-10-03" payé="5.00">Marie Dupont</visiteur>
    </visites>
  </musée>
  <musée idmusée="man">
    <nom>Matisse</nom><ville>Nice</ville>
    <visites>
      <visiteur date="2021-10-03" payé="8.00">Kévin Martin</visiteur>
      <visiteur date="2021-10-04" payé="10.00">Victor Martin</visiteur>
    </visites>
  </musée>
  <objet-art musée="lop" type= "peinture">
    <intitulé>La Joconde</intitulé>
    <auteur>Léonard de Vinci</auteur>
    <description>Peinture à l'<matériau>huile</matériau> sur <matériau>panneau de bois</matériau></description>
  </objet-art>
  <objet-art musée="lop" type="sculpture">
    <intitulé>Vénus de Milo</intitulé>
    <description>Statue grecque en <matériau>marbre</matériau></description>
  </objet-art>
</musées>
